name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  isocalendar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: shaafsalman
          template: classic
          base: ""
          config_timezone: Asia/Karachi
          filename: metrics.plugin.isocalendar.fullyear.svg
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

  languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: shaafsalman
          template: classic
          base: ""
          config_timezone: Asia/Karachi
          filename: metrics.plugin.languages.indepth.svg
          
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: 0:#000000, 1:#1a1a1a, 2:#333333, 3:#4d4d4d, 4:#808080, 5:#a6a6a6, 6:#c0c0c0, 7:#ffffff
          plugin_languages_threshold: 0%
